-- Practical Fitness Coach Platform
-- Canonical exercise master log (Michael's list, PRD Appendix A/B).
-- 66 exercises across Upper Body / Lower Body, with default movement
-- classification, machine, body section, and muscle group.

insert into exercises
  (name, abbreviation, exercise_type, default_movement_classification, is_fundamental, machine_name, body_section, muscle_group)
values
  ('Hip Press', 'HP', 'A', 'D', true, 'Hip Press Machine', 'Lower Body', 'Quadriceps'),
  ('Hip Press (R)', 'HP(R)', 'C', 'E', false, 'Hip Press Machine', 'Lower Body', 'Quadriceps'),
  ('Hip Press (L)', 'HP(L)', 'C', 'E', false, 'Hip Press Machine', 'Lower Body', 'Quadriceps'),
  ('Leg Extension', 'LEGX', 'C', 'D', false, 'Leg Extension Machine', 'Lower Body', 'Quadriceps'),
  ('Bodyweight Squat', 'BWS', 'C', 'M', false, 'No machine', 'Lower Body', 'Quadriceps'),
  ('Hip Bridge', 'HBR', 'C', 'M', false, 'No machine', 'Lower Body', 'Hamstrings'),
  ('Leg Curls (Medex or CLX Theraband)', 'LCR', 'C', 'D', false, 'Leg Curl Machine or Theraband', 'Lower Body', 'Hamstrings'),
  ('Nordic Leg Curl', 'NLC', 'C', 'M', false, 'No machine', 'Lower Body', 'Hamstrings'),
  ('Adduction (anchored band + freedom trainer)', 'ADD1', 'C', 'M', false, 'Freedom Trainer', 'Lower Body', 'Inner Thigh'),
  ('Adduction (off the exercise bench)', 'ADD2', 'C', 'M', false, 'Exercise Bench', 'Lower Body', 'Inner Thigh'),
  ('Adduction (on the floor with bottom leg)', 'ADD3', 'C', 'M', false, 'No machine', 'Lower Body', 'Inner Thigh'),
  ('Hip Press with Seatback 3', 'HPSB3', 'C', 'D', false, 'Hip Press Machine', 'Lower Body', 'Glutes & Rear End'),
  ('Hip Press with Seatback 3 (R)', 'HPSB3(R)', 'C', 'E', false, 'Hip Press Machine', 'Lower Body', 'Glutes & Rear End'),
  ('Hip Press with Seatback 3 (L)', 'HPSB3(L)', 'C', 'E', false, 'Hip Press Machine', 'Lower Body', 'Glutes & Rear End'),
  ('Single Leg Bridge', 'SLB', 'C', 'M', false, 'No machine', 'Lower Body', 'Glutes & Rear End'),
  ('Kickback or Donkey Kick', 'KDK', 'C', 'M', false, 'No machine', 'Lower Body', 'Glutes & Rear End'),
  ('Standing/Lying/Freedom Trainer Abduction', 'ABD', 'C', 'M', false, 'Freedom Trainer', 'Lower Body', 'Glutes & Rear End'),
  ('Hip Bridge with Torso Extension', 'HBTE', 'C', 'M', false, 'No machine', 'Lower Body', 'Glutes & Rear End'),
  ('Split Squat', 'SPSQ', 'C', 'D', false, 'No machine', 'Lower Body', 'Glutes & Rear End'),
  ('Knee Lift', 'KL', 'C', 'M', false, 'No machine', 'Lower Body', 'Hip Flexors'),
  ('Hip Flexor with Bent Knee', 'HFBK', 'C', 'M', false, 'No machine', 'Lower Body', 'Hip Flexors'),
  ('Hip Flexor with Straight Leg', 'HFSL', 'C', 'M', false, 'No machine', 'Lower Body', 'Hip Flexors'),
  ('Table Top Leg Raise', 'TTLR', 'C', 'M', false, 'No machine', 'Lower Body', 'Hip Flexors'),
  ('Calf Raise (Bilateral or Single Leg)', 'CR', 'C', 'M', false, 'No machine', 'Lower Body', 'Calves'),
  ('Seated Calf Raise', 'SCR', 'C', 'M', false, 'No machine', 'Lower Body', 'Calves'),
  ('Chest Press', 'CP', 'B', 'D', true, 'Chest Press Machine', 'Upper Body', 'Chest'),
  ('Chest Fly (Dumbbells or Freedom Trainer)', 'CFLY', 'C', 'D', false, 'Fly Machine or Dumbbells', 'Upper Body', 'Chest'),
  ('Push Plank', 'PPL', 'C', 'M', false, 'No machine', 'Upper Body', 'Chest'),
  ('Pushups', 'PU', 'C', 'M', false, 'No machine', 'Upper Body', 'Chest'),
  ('Incline or Overhead Press', 'OHP', 'B', 'D', true, 'Incline/OHP Machine', 'Upper Body', 'Shoulders'),
  ('Lateral Raise', 'LAT', 'C', 'D', false, 'No machine', 'Upper Body', 'Shoulders'),
  ('Rear Fly', 'RFLY', 'C', 'D', false, 'Fly Machine', 'Upper Body', 'Shoulders'),
  ('Pull Over', 'PLO', 'C', 'D', false, 'No machine', 'Upper Body', 'Shoulders'),
  ('Anterior Delt Raise', 'ADR', 'C', 'D', false, 'No machine', 'Upper Body', 'Shoulders'),
  ('Pull Down', 'PD', 'B', 'D', true, 'Pull Down Machine', 'Upper Body', 'Upper Back'),
  ('Row', 'RW', 'B', 'D', true, 'Row Machine', 'Upper Body', 'Upper Back'),
  ('Rear Fly (Dumbbells or Freedom Trainer)', 'RDFL', 'C', 'D', false, 'Dumbbells or Freedom Trainer', 'Upper Body', 'Upper Back'),
  ('Pull Over (Cable Apparatus or Band)', 'PLOB', 'C', 'D', false, 'Cable or Band', 'Upper Body', 'Upper Back'),
  ('Shrug (Dumbbells or Band or Freedom Trainer)', 'SHR', 'C', 'M', false, 'Dumbbells or Band', 'Upper Body', 'Upper Back'),
  ('Upright Row with Freedom Trainer', 'URW', 'C', 'D', false, 'Freedom Trainer', 'Upper Body', 'Upper Back'),
  ('Bicep Curl', 'BC', 'C', 'D', false, 'Dumbbells or Machine', 'Upper Body', 'Biceps'),
  ('Concentrated Unilateral Bicep Curl', 'CUBC', 'C', 'D', false, 'Dumbbells', 'Upper Body', 'Biceps'),
  ('Hammer Curl', 'HC', 'C', 'D', false, 'Dumbbells', 'Upper Body', 'Biceps'),
  ('Zatman Curl', 'ZC', 'C', 'D', false, 'Dumbbells', 'Upper Body', 'Biceps'),
  ('Tricep Extension Overhead', 'TEO', 'C', 'D', false, 'No machine', 'Upper Body', 'Triceps'),
  ('Pushdown', 'PSD', 'C', 'D', false, 'Cable Machine', 'Upper Body', 'Triceps'),
  ('Skull Crusher', 'SKC', 'C', 'D', false, 'Dumbbells or Bar', 'Upper Body', 'Triceps'),
  ('Tricep Kickback Cable Version', 'TRIX', 'C', 'M', false, 'Cable Machine', 'Upper Body', 'Triceps'),
  ('Pushup (1/4 micro-movement or muscle led)', 'PUML', 'C', 'E', false, 'No machine', 'Upper Body', 'Triceps'),
  ('AB ISO', 'ISO', 'A', 'D', true, 'Ab ISO Machine', 'Upper Body', 'Abs & Torso'),
  ('Plank', 'PLK', 'C', 'M', false, 'No machine', 'Upper Body', 'Abs & Torso'),
  ('Leg Raise', 'LGR', 'C', 'M', false, 'No machine', 'Upper Body', 'Abs & Torso'),
  ('Reverse Ab Crunch', 'RAC', 'C', 'M', false, 'No machine', 'Upper Body', 'Abs & Torso'),
  ('Hip Cross Over', 'HCO', 'C', 'E', false, 'No machine', 'Upper Body', 'Abs & Torso'),
  ('V Up', 'VU', 'C', 'D', false, 'No machine', 'Upper Body', 'Abs & Torso'),
  ('Side Plank', 'SPLK', 'C', 'M', false, 'No machine', 'Upper Body', 'Abs & Torso'),
  ('Situp', 'SITUP', 'C', 'M', false, 'No machine', 'Upper Body', 'Abs & Torso'),
  ('V Sit', 'VUP', 'C', 'D', false, 'No machine', 'Upper Body', 'Abs & Torso'),
  ('Reverse Wrist Curl', 'RWC', 'C', 'M', false, 'No machine', 'Upper Body', 'Forearms Hands & Grip'),
  ('Two-Finger Wrist Curl', 'TFWC', 'C', 'M', false, 'No machine', 'Upper Body', 'Forearms Hands & Grip'),
  ('Wrist Curl (Dumbbell or Freedom Trainer)', 'WC', 'C', 'M', false, 'Dumbbells or Freedom Trainer', 'Upper Body', 'Forearms Hands & Grip'),
  ('Lumbar Extension', 'LX', 'A', 'D', true, 'Lumbar Extension Machine', 'Lower Body', 'Lower Back'),
  ('Assisted Chin Up', 'ASCU', 'C', 'D', false, 'Assisted Chin Up Machine', 'Upper Body', 'Upper Back'),
  ('Assisted Dip', 'DIP', 'C', 'D', false, 'Assisted Dip Machine', 'Upper Body', 'Triceps'),
  ('Metabolic Hip Press', 'MHP', 'A', 'M', true, 'Hip Press Machine', 'Lower Body', 'Quadriceps'),
  ('Rotary Torso', 'RT', 'C', 'D', false, 'Rotary Torso Machine', 'Upper Body', 'Abs & Torso');
